name: CI/CD Node App to DockerHub and EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Update Kubernetes Deployment
      run: |
        aws eks update-kubeconfig --region ap-southeast-1 --name simple-node-cluster
        kubectl set image deployment/node-app node-app=${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest
